[package]
name = "letterchain-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
rustc-hash = "2.0"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"

[[bin]]
name = "letterchain-rust"
path = "main.rs"
